

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "solana_transfer_program"
version = "0.1.0"
edition = "2018"

[dependencies]
solana-program = "1.10"

[lib]
crate-type = ["cdylib", "lib"]
